[package]
name = "desert-server"
version = "0.1.0"
authors = ["Jan Jansen <farodin91@googlemail.com>"]

[dependencies]
clap = "2.13.0"
clippy = "*"
diesel = "0.7.1"
hyper = "0.9.10"
log = "0.3.6"
serde = "0.8.10"
serde_macros = "0.8.9"
serde_json = "0.8.2"
term = "0.4.4"
tokio-core = "0.1.0"
