[package]
name = "desert-server"
version = "0.1.0"
authors = ["Jan Jansen <farodin91@googlemail.com>"]

[dependencies]
log = "0.3.6"
env_logger = "0.3.5"
clap = "2.13.0"
tokio-core = "0.1.0"
serde = "0.8.10"
serde_json = "0.8.2"
term = "0.4.4"
